from markupsafe import Markup

from odoo import api, fields, models
from odoo.exceptions import UserError


class ClientPurchaseOrderLine(models.Model):
    _name = 'jewelry.client.purchase.line'
    _description = 'Client Purchase Order Line'
    _order = 'order_id, sequence, id'

    order_id = fields.Many2one(
        comodel_name='jewelry.client.purchase',
        string='Order',
        required=True,
        ondelete='cascade',
        index=True,
    )
    sequence = fields.Integer(
        string='Sequence',
        default=10,
    )
    description = fields.Text(
        string='Description',
        required=True,
        help='Detailed description of the item',
    )
    jewelry_type_id = fields.Many2one(
        comodel_name='jewelry.type',
        string='Tipo de Joya',
        help='Tipo de artículo (ej: Anillo, Collar). Se sugiere automáticamente según la descripción.',
    )
    quality_id = fields.Many2one(
        comodel_name='jewelry.material.quality',
        string='Quality',
        help='Material quality (e.g., 18k gold, sterling silver)',
    )
    weight = fields.Float(
        string='Weight (g)',
        digits=(10, 3),
        help='Weight in grams',
    )
    price = fields.Monetary(
        string='Amount',
        required=True,
        help='Amount paid to client for this item',
    )
    currency_id = fields.Many2one(
        related='order_id.currency_id',
        store=True,
    )
    company_id = fields.Many2one(
        related='order_id.company_id',
        store=True,
    )
    state = fields.Selection(
        related='order_id.state',
        store=True,
    )

    # Image attachments
    image_ids = fields.Many2many(
        comodel_name='ir.attachment',
        relation='client_purchase_line_image_rel',
        column1='line_id',
        column2='attachment_id',
        string='Photos',
        help='Photos of the item for documentation',
    )
    image_count = fields.Integer(
        string='Photo Count',
        compute='_compute_image_count',
    )
    image_preview = fields.Html(
        string='Preview',
        compute='_compute_image_preview',
        sanitize=False,
    )
    image_description = fields.Text(
        string='Photo Description',
        help='Description of the items shown in the photos',
    )

    # AI Vision integration (prepared for future use)
    ai_description = fields.Text(
        string='AI Description',
        readonly=True,
        copy=False,
        help='Description generated by AI vision model',
    )
    ai_model = fields.Char(
        string='AI Model',
        readonly=True,
        copy=False,
        help='Model that generated the description (e.g., gpt-4-vision)',
    )
    ai_generated_date = fields.Datetime(
        string='AI Analysis Date',
        readonly=True,
        copy=False,
    )
    ai_confidence = fields.Float(
        string='AI Confidence',
        readonly=True,
        copy=False,
        digits=(3, 2),
        help='Confidence score from the AI model (0-1)',
    )

    # Optional product link (for items that become inventory)
    product_id = fields.Many2one(
        comodel_name='product.product',
        string='Created Product',
        readonly=True,
        help='Product created from this line when processed',
    )

    # Line processing state
    line_state = fields.Selection(
        selection=[
            ('pending', 'Pending'),
            ('in_inventory', 'In Inventory'),
            ('to_smelting', 'To Smelting'),
        ],
        string='Line State',
        default='pending',
        required=True,
        help='Processing state of this line item',
    )
    smelting_batch_id = fields.Many2one(
        comodel_name='jewelry.smelting.batch',
        string='Smelting Batch',
        readonly=True,
        index=True,
        help='Batch reference when this item was sent to smelting',
    )

    @api.depends('image_ids')
    def _compute_image_count(self):
        for line in self:
            line.image_count = len(line.image_ids)

    @api.depends('image_ids')
    def _compute_image_preview(self):
        for line in self:
            if not line.image_ids:
                line.image_preview = False
                continue
            html_parts = ['<div class="d-flex flex-wrap gap-2">']
            for attachment in line.image_ids:
                # Use web/content for attachments with access_token for security
                url = f'/web/image/{attachment.id}?access_token={attachment.access_token}' \
                    if attachment.access_token else f'/web/image/{attachment.id}'
                html_parts.append(
                    f'<a href="{url}" target="_blank">'
                    f'<img src="{url}" '
                    f'style="max-height:120px;max-width:150px;object-fit:cover;'
                    f'border:1px solid #dee2e6;border-radius:8px;" '
                    f'title="{attachment.name}" loading="lazy"/>'
                    f'</a>'
                )
            html_parts.append('</div>')
            line.image_preview = Markup(''.join(html_parts))

    @api.onchange('quality_id')
    def _onchange_quality_id(self):
        """Auto-fill description with quality name if empty."""
        if self.quality_id and not self.description:
            self.description = self.quality_id.name

    @api.onchange('description')
    def _onchange_description_infer_type(self):
        """Auto-suggest jewelry type based on description keywords."""
        if self.description and not self.jewelry_type_id:
            JewelryType = self.env['jewelry.type']
            inferred_type = JewelryType.infer_from_description(self.description)
            if inferred_type:
                self.jewelry_type_id = inferred_type

    def action_view_images(self):
        """Open images in a gallery view."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': f'Photos - {self.description or "Item"}',
            'res_model': 'ir.attachment',
            'view_mode': 'kanban,form',
            'domain': [('id', 'in', self.image_ids.ids)],
            'context': {
                'default_res_model': self._name,
                'default_res_id': self.id,
            },
        }

    def action_send_to_inventory(self):
        """Open wizard to send this line item to inventory."""
        self.ensure_one()
        if self.line_state != 'pending':
            raise UserError('Only pending items can be sent to inventory.')
        if self.order_id.state != 'available':
            raise UserError(
                'Items can only be sent to inventory when the order is in Available state.'
            )
        return {
            'type': 'ir.actions.act_window',
            'name': 'Send to Inventory',
            'res_model': 'jewelry.send.to.inventory.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_line_id': self.id,
                'default_product_name': self.description,
            },
        }

    def action_send_to_smelting(self):
        """Mark this line as sent to smelting."""
        self.ensure_one()
        if self.line_state != 'pending':
            raise UserError('Only pending items can be sent to smelting.')
        if self.order_id.state != 'available':
            raise UserError(
                'Items can only be sent to smelting when the order is in Available state.'
            )

        self.write({'line_state': 'to_smelting'})

        # Log to chatter
        self.order_id.message_post(
            body=f"Item '<b>{self.description}</b>' sent to smelting.",
            subject='Item sent to smelting',
            message_type='notification',
        )

        # Check if all lines are now processed
        self._check_order_completion()

        return True

    def _check_order_completion(self):
        """Check if all lines in the order are processed and auto-transition."""
        order = self.order_id
        if order.state != 'available':
            return

        if all(line.line_state != 'pending' for line in order.line_ids):
            order.action_process()

    def _get_line_number(self):
        """Get the line position within the order (1-based)."""
        self.ensure_one()
        lines = self.order_id.line_ids.sorted(key=lambda l: (l.sequence, l.id))
        for idx, line in enumerate(lines, start=1):
            if line.id == self.id:
                return idx
        return 1

    def _generate_sku(self):
        """Generate SKU based on purchase reference and line number."""
        self.ensure_one()
        order_ref = self.order_id.name or ''
        line_num = self._get_line_number()
        return f"{order_ref}-{line_num}"
